config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :vessels, except: :show

  namespace :admin do
    resources :vessels, except: :show
  end

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root to: 'vessels#index'
end

app/models/user.rb
class User < ActiveRecord::Base
    validates :name, presence: true
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: true
    has_secure_password
    validates :password, presence: true
end

app/models/vessel.rb
class Vessel < ActiveRecord::Base
  validates :title, :description, :daily_price, :presence => true
  validates :daily_price, :numericality => true
end

app/controllers/admin/vessels_controller.rb
class Admin::VesselsController < ApplicationController
  layout 'admin'
  before_action :require_admin
  before_action :set_vessel, only: [:show, :edit, :update, :destroy]

  # GET /vessels
  # GET /vessels.json
  def index
    @vessels = Vessel.all
  end

  # GET /vessels/new
  def new
    @vessel = Vessel.new
  end

  # GET /vessels/1/edit
  def edit
  end

  # POST /vessels
  # POST /vessels.json
  def create
    @vessel = Vessel.new(vessel_params)

    respond_to do |format|
      if @vessel.save
        format.html { redirect_to admin_vessels_url, notice: 'Vessel was successfully created.' }
        format.json { render :show, status: :created, location: @vessel }
      else
        format.html { render :new }
        format.json { render json: @vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vessels/1
  # PATCH/PUT /vessels/1.json
  def update
    respond_to do |format|
      if @vessel.update(vessel_params)
        format.html { redirect_to admin_vessels_url, notice: 'Vessel was successfully updated.' }
        format.json { render :show, status: :ok, location: @vessel }
      else
        format.html { render :edit }
        format.json { render json: @vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vessels/1
  # DELETE /vessels/1.json
  def destroy
    @vessel.destroy
    respond_to do |format|
      format.html { redirect_to admin_vessels_url notice: 'Vessel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vessel
      @vessel = Vessel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vessel_params
      params.require(:vessel).permit(:title, :description, :daily_price, :fee_pc)
    end

    def require_admin
      if current_user.nil? or !current_user.admin?
        flash[:error] = "You must be an admin to access this section"
        redirect_to login_url
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to root_path
    end
  end

  def create
    if logged_in?
      redirect_to root_url
    end
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to index page.
      log_in user
      redirect_to root_url
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/vessels_controller.rb
class VesselsController < ApplicationController
  before_action :set_vessel, only: [:show, :edit, :update, :destroy]

  # GET /vessels
  # GET /vessels.json
  def index
    @vessels = Vessel.all
  end

  # GET /vessels/new
  def new
    @vessel = Vessel.new
  end

  # GET /vessels/1/edit
  def edit
  end

  # POST /vessels
  # POST /vessels.json
  def create
    @vessel = Vessel.new(vessel_params)

    respond_to do |format|
      if @vessel.save
        if current_user.nil? or !current_user.admin?
          AdminMailer.notify_vessel_created(request.ip, @vessel).deliver_later
        end
        format.html { redirect_to vessels_url, notice: 'Vessel was successfully created.' }
        format.json { render :show, status: :created, location: @vessel }
      else
        format.html { render :new }
        format.json { render json: @vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vessels/1
  # PATCH/PUT /vessels/1.json
  def update
    respond_to do |format|
      if @vessel.update(vessel_params)
        if current_user.nil? or !current_user.admin?
          AdminMailer.notify_vessel_updated(request.ip, @vessel, vessel_params).deliver_later
        end
        format.html { redirect_to vessels_url, notice: 'Vessel was successfully updated.' }
        format.json { render :show, status: :ok, location: @vessel }
      else
        format.html { render :edit }
        format.json { render json: @vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vessels/1
  # DELETE /vessels/1.json
  def destroy
    @vessel.destroy
    respond_to do |format|
      format.html { redirect_to vessels_url, notice: 'Vessel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vessel
      @vessel = Vessel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vessel_params
      params.require(:vessel).permit(:title, :description, :daily_price)
    end
end

app/helpers/admin/vessels_helper.rb
module Admin::VesselsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/vessels_helper.rb
module VesselsHelper
end

app/views/admin/vessels/_form.html.erb
<%= form_for([:admin, @vessel]) do |f| %>
  <% if @vessel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vessel.errors.count, "error") %> prohibited this vessel from being saved:</h2>

      <ul>
      <% @vessel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <dl class='form-fields'>
    <dt><%= f.label :title, 'Title:' %></dt>
    <dd><%= f.text_field :title %></dd>

    <dt><%= f.label :description, 'Description:' %></dt>
    <dd><%= f.text_area :description %></dd>

    <dt><%= f.label :daily_price, 'Daily Price:' %></dt>
    <dd><%= f.text_field :daily_price %></dd>

    <dt><%= f.label :fee_pc, 'Fee %:' %></dt>
    <dd><%= f.text_field :fee_pc %></dd>
  </dl>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/vessels/edit.html.erb
<h1>Editing Vessel</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_vessels_path %>

app/views/admin/vessels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vessels</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Daily price</th>
      <th>Fee %</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @vessels.each do |vessel| %>
      <tr>
        <td><%= vessel.title %></td>
        <td><%= number_to_currency(vessel.daily_price) %></td>
        <td><%= number_to_percentage(vessel.fee_pc) %></td>
        <td><%= link_to 'Edit', edit_admin_vessel_path(vessel) %></td>
        <td><%= link_to 'Destroy', admin_vessel_path(vessel), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vessel', new_admin_vessel_path %>

app/views/admin/vessels/new.html.erb
<h1>New Vessel</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_vessels_path %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='top admin'>
  Testapp - Admin
</div>
<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='top'>
  Testapp - User
</div>
<div class="nav">
  <% if logged_in? %>
    <p>Welcome <%= current_user.name %></p>
    <% if current_user.admin? %>
      <%= link_to "Go to admin", admin_vessels_path %>
    <% end %>
    <%= link_to "Log out", logout_path, method: :delete %>
  <% elsif !current_page?(controller: 'sessions', action: 'create') %>
    <%= link_to "Log in", login_path, method: :get %>
  <% end %>
</div>
<%= yield %>
<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/vessels/_form.html.erb
<%= form_for(@vessel) do |f| %>
  <% if @vessel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vessel.errors.count, "error") %> prohibited this vessel from being saved:</h2>

      <ul>
      <% @vessel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <dl class='form-fields'>
    <dt><%= f.label :title, 'Title:' %></dt>
    <dd><%= f.text_field :title %></dd>

    <dt><%= f.label :description, 'Description:' %></dt>
    <dd><%= f.text_area :description %></dd>

    <dt><%= f.label :daily_price, 'Daily Price:' %></dt>
    <dd><%= f.text_field :daily_price %></dd>
  </dl>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vessels/edit.html.erb
<h1>Editing Vessel</h1>

<%= render 'form' %>

<%= link_to 'Back', vessels_path %>

app/views/vessels/index.html.erb
<p id="notice"><%= notice %></p>
<% if flash[:error] -%>
  <p class='error'><%=h flash[:error] %></p>
<% end -%>
<h1>Listing Vessels</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Daily price</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @vessels.each do |vessel| %>
      <tr>
        <td><%= vessel.title %></td>
        <td><%= number_to_currency(vessel.daily_price) %></td>
        <td><%= link_to 'Edit', edit_vessel_path(vessel) %></td>
        <td><%= link_to 'Destroy', vessel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vessel', new_vessel_path %>

app/views/vessels/new.html.erb
<h1>New Vessel</h1>

<%= render 'form' %>

<%= link_to 'Back', vessels_path %>